id: P2CB19520
initial_creation_type: input
source_metadata:
  title: Abhisamayālaṃkāra Series
  language: en
  description: 'Texts related to the Abhisamayālaṃkāra (mngon rtogs rgyan) or Clear
    Ornament of Realization, one of the Five Treatises of Maitreyanātha:'
  volume:
    89ed98f0a5874cb383ae8c1c31237ba5:
      title: 'Words from the Lineage Masters to Clarify Maitreyanātha''s Vision: An
        Overview of the Perfection of Wisdom''s Ornament of Realization'
      parent: Commentaries
    4cd65645402d40cf84d8674bff7887ca:
      title: Prologue to Abhisamayālaṃkāra Commentary
      parent: Commentaries
    afc43e5f4aa245c891fd84e35a528564:
      title: A Preliminary to the Explanation of the Prajñāpāramitā
      parent: Commentaries
    0fc769d69d2c4d54b5e59696f8f4417b:
      title: 'The Words of Jigme Chökyi Wangpo: A Commentary Presenting the Subject
        Matter of the Great Treatise Abhisamayālaṃkāra'
      parent: Commentaries
    65dbda7d3234432fb857fe062bb70bfb:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Commentaries
    1059c9626dd84d55902865980ac6cd93:
      title: The Eightfold Nature of Profundity from the Abhisamayālaṃkāra
      parent: Notes
created_at: '2022-03-01T02:29:29.031678'
last_modified_at: '2022-03-01T02:29:29.031687'
